name: "PR Title Checker"
on:
  pull_request_target:
    types: [opened, reopened, edited]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Validate pull request title format
        run: |
          title=$(echo "${{ github.event.pull_request.title }}")
          pattern="^(\[(FEATURE|BUGFIX|HOTFIX|CHORE|REFACTOR|TEST)\])\[[A-Z]+-[0-9]+\]\s[a-zA-Z]+.*$"
          if [[ "$title" =~ $pattern ]]; then
            echo "Pull request title is not in the expected format"
            echo "Title should match pattern: $pattern"
          else
            echo "Título inválido. O título deve seguir o padrão '[TIPO][ID-123] Descrição'. Por favor, corrija o título do pull request."
            gh pr comment ${{ github.event.pull_request.number }} --body "O título do pull request é inválido. Por favor, corrija o título seguindo o padrão '[TIPO][ID-123] Descrição'."
            exit 1
          fi

      - name: Finalize job
        run: echo "Pull Request title validation completed."
