name: "PR Title Checker"
on:
  pull_request_target:
    types: [opened, reopened, edited]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate pull request title format
        run: |
          title=$(echo "${{ github.event.pull_request.title }}" | tr -d '\n')
          pattern="^(\[FEATURE\]|\[BUGFIX\]|\[HOTFIX\]|\[CHORE\]|\[REFACTOR\]|\[TEST\])\[[A-Za-z0-9-]+\]\s[a-zA-Z]+$"
          if ! [[ "$title" =~ $pattern ]]; then
            echo "Pull request title is not in the expected format"
            echo "Title should match pattern: $pattern"
            exit 1
          fi
